services:
    php:
        container_name: app-php
        environment:
            - TZ=America/Manaus
        build:
            dockerfile: ./devops/php/Dockerfile
        volumes:
            - ./:/backend:rw
            - ./devops/php/php.ini:/usr/local/etc/php/php.ini:ro
        restart: always
        command: ["/backend/start.sh"]
        expose:
            - "9000"
        depends_on:
            - postgres

    apache:
        build:
            dockerfile: ./devops/apache2/Dockerfile
        container_name: app-apache
        depends_on:
            - php
        ports:
            - "3543:80"
            - "3544:443"
        restart: always
        volumes:
            - ./:/backend:rw
            - ./devops/apache2/sites-enabled:/etc/apache2/sites-enabled

    postgres:
        image: postgres:16-alpine
        container_name: app-postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-laravel}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-laravel} -d ${DB_DATABASE:-laravel}"]
            interval: 5s
            timeout: 5s
            retries: 20

    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: app-frontend
        environment:
            - TZ=America/Manaus
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - VITE_API_BASE_URL=http://localhost:3543
        volumes:
            - ../frontend:/app:rw
            - /app/node_modules
        ports:
            - "5173:5173"
        command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
        depends_on:
            - apache

volumes:
    pgdata:
